--- Makefile	2014-01-27 01:30:27.720384985 +0100
+++ Makefile	2014-02-15 00:44:23.375867879 +0100
@@ -4,6 +4,7 @@
 
 obj-y = clock/
 obj-y += dma/
+obj-y += rf/
 obj-$(CONFIG_CPU_FREQ)			+= cpu-freq/
 obj-$(CONFIG_PM) += pm/
 obj-$(CONFIG_AW_TIME_DELAY)	+= delay.o
